---
title: "GIS_Part 3"
author: "B.Z."
date: "December 29, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(spatstat)
library(sp)
library(rgeos)
library(maptools)
library(GISTools)
library(tmap)
library(sf)
library(geojsonio)
library(tmaptools)
library(raster)
library(fpc)
library(plyr)
library(OpenStreetMap)
library(rgdal)
library(tidyverse)
library(broom)
library(ggplot2)
library(spdep)
library(corrplot)
```


Data setting up

```{r code1, echo=FALSE}

BoroughMapSF <- read_shape("BoundaryData/england_lad_2011.shp", as.sf = TRUE)
LondonWards <- readOGR("WardsData/LondonWards.shp", layer="LondonWards")
BoroughMap <- as(BoroughMapSF, "Spatial")
Wastepoint <- geojson_read("point.geojson", what = "sp")
Wardsdata <- read.csv("Rawdata.csv")
LondonWardsSF <- st_as_sf(LondonWards)
LondonWardsSF <- merge(LondonWardsSF,Wardsdata, by.x="WD11CD", by.y="New.ward.code")
LondonWards <- as(LondonWardsSF,"Spatial")
```



```{r code2, echo=FALSE}
tmap_mode('view')
summary(Wastepoint)
BNG = "+init=epsg:27700"
LondonWardsBNG <- spTransform(LondonWards,BNG)
BoroughMapBNG <- spTransform(BoroughMap,BNG)
BoroughBNGSF <- st_as_sf(BoroughMapBNG)
WastepointBNG <- spTransform(Wastepoint, BNG)
tm_shape(BoroughMapBNG) +
  tm_polygons(col = NA, alpha = 1.0) +
  tm_shape(WastepointBNG) +
  tm_dots(col = "blue")
#Here we can find some points lay out the boundaries, thus we need clip the points to make all points are in boundary.
WastepointBNG <- WastepointBNG[BoroughMapBNG,]
summary(Wastepoint)
tm_shape(BoroughMapBNG) +
  tm_polygons(col = NA, alpha = 0.5) +
  tm_shape(WastepointBNG) +
  tm_dots(col = "blue")
```
Then we employed poly.counts funtion to count 


```{r code3, echo=FALSE}
library(spatialEco)
Londoninone <- BoroughBNGSF
Londoninone$agg <- 1
Londonagg <- Londoninone %>% group_by(Londoninone$agg) %>% summarise()
londonaggSP <- as(Londonagg,"Spatial")


window <- as.owin(londonaggSP)
plot(window)
Wastepoint.ppp <- ppp(x=WastepointBNG@coords[,1],y=WastepointBNG@coords[,2],window=window)
K <- Kest(Wastepoint.ppp, correction="border")
plot(K)
nni(WastepointBNG,win = "extent")
Wastepoints <- data.frame(WastepointBNG@coords[,1:2])
#now run the dbscan analysis
db <- fpc::dbscan(Wastepoints, eps = 1500, MinPts = 3)
#now plot the results
plot(db, Wastepoints, main = "DBSCAN Output", frame = F)
plot(londonaggSP, add=T)
db


```


```{r code4, echo=FALSE}

res <- poly.counts(WastepointBNG, LondonWardsBNG)
LondonWardsBNG@data$WastepointCount<-res
LondonWardsBNG@data$WasteDensity <- LondonWardsBNG$WastepointCount/poly.areas(LondonWardsBNG)*1000000
tm_shape(LondonWardsBNG) +
  tm_polygons("WasteDensity",
              style="cont",
              palette="Oranges",
              midpoint=NA,
              title="Waste Point Density")
```




```{r code5, echo=FALSE}
coordsW <- coordinates(LondonWardsBNG)
plot(LondonWardsBNG)
LB_nb <- poly2nb(LondonWardsBNG, queen=T)
#plot them
plot(LB_nb, coordinates(LondonWardsBNG), col="red")
#add a map underneath
plot(LondonWardsBNG, add=T)
Lward.lw <- nb2listw(LB_nb, style="C")
I_LWard_Global_Density <- moran.test(LondonWardsBNG@data$WasteDensity, Lward.lw)
I_LWard_Global_Density


G_LWard_Global_Density <- globalG.test(LondonWardsBNG@data$WasteDensity, Lward.lw)
G_LWard_Global_Density

I_LWard_Local <- localmoran(LondonWardsBNG@data$WastepointCount, Lward.lw)
I_LWard_Local_Density <- localmoran(LondonWardsBNG@data$WasteDensity, Lward.lw)

LondonWardsBNG@data$BLocI <- I_LWard_Local[,1]
LondonWardsBNG@data$BLocIz <- I_LWard_Local[,4]
LondonWardsBNG@data$BLocIR <- I_LWard_Local_Density[,1]
LondonWardsBNG@data$BLocIRz <- I_LWard_Local_Density[,4]
summary(LondonWardsBNG@data$BLocIRz)
MoranColours<- rev(brewer.pal(6, "RdGy"))
breaks1<-c(-1000,-1,-0.5,0,0.5,1,1000)

#now plot on an interactive map
tm_shape(LondonWardsBNG) +
    tm_polygons("BLocIRz",
        style="fixed",
        breaks=breaks1,
        palette=MoranColours,
        midpoint=NA,
        title="Local Moran's I, Waste point in London")

Gi_LWard_Local_Density <- localG(LondonWardsBNG@data$WasteDensity, Lward.lw)
LondonWardsBNG@data$BLocGiRz <- Gi_LWard_Local_Density
summary(LondonWardsBNG@data$BLocGiRz)

GIColours<- rev(brewer.pal(6, "RdBu"))
breaks2<-c(-1000,-1.17,-0.78,-0.27,0.083,2,1000)
#now plot on an interactive map
tm_shape(LondonWardsBNG) +
    tm_polygons("BLocGiRz",
        style="fixed",
        breaks=breaks2,
        palette=GIColours,
        midpoint=NA,
        title="Gi*, Blue Plaques in London")
```


```{r code6, echo=FALSE}
newvar<-0
LondonWardsSF <- st_as_sf(LondonWardsBNG)
attach(LondonWardsSF)
newvar<-0
recodecount<-function(variable){
  newvar[variable>0]<-"WithWaste"
  newvar[variable==0]<-"WithoutWaste"
  return(newvar)
}
LondonWardsSF$WastepointCount_recode <- recodecount(WastepointCount)
tm_shape(LondonWardsSF) +
  tm_polygons("WastepointCount_recode",
              style="cat",
              palette="Reds",
              midpoint=NA,
              title="If ward having any wastepoint")

```



```{r code7, echo=FALSE}
newvar <- 0
recode<-function(variable,high,medium,low){
  newvar[variable<=high]<-"High"
  newvar[variable<=medium]<-"Medium"
  newvar[variable<=low]<-"Low"
  return(newvar)
}

summary(LondonWardsSF$Unemployment.rate.2013)
LondonWardsSF$Unemployment.rate.2013_recode <- recode(Unemployment.rate.2013,23.5,8.1,3.2)
chisq<-chisq.test(LondonWardsSF$Unemployment.rate.2013_recode,LondonWardsSF$WastepointCount_recode)
chisq$observed
chisq$expected
chisq$p.value






```


```{r code8, echo=FALSE}
WithWaste <- subset(LondonWardsSF, WastepointCount_recode== "WithWaste")
WithWasteDF <- st_set_geometry(WithWaste,NULL)


varlist <- data.frame(cbind(lapply(WithWasteDF, class)))
varlist$id <- seq(1,nrow(varlist))

WithWasteDF$Unemployment.rate.2013 <- as.numeric(WithWasteDF$Unemployment.rate.2013)
cormat2 <- cor(WithWasteDF[,c(142,115,100,85)], use="complete.obs", method="pearson")
corrplot(cormat2)



qplot(WasteDensity,Unemployment.rate.2013 , data = WithWaste, geom = "point")
model1 <- lm(Unemployment.rate.2013 ~ WasteDensity, data = WithWaste)
model1_res <- tidy(model1)
summary(model1)
model2 <- lm(Crime.rate...2013 ~ WasteDensity, data = WithWaste)
WithWaste$model1_res <- model1$residuals
WithWaste$model2_res <- model2$residuals

summary(model2)
qtm(WithWaste, fill = "model1_res")
qtm(WithWaste, fill = "model2_res")

```


